version: '3.7'

services:
  mongodb:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=dhs
      - MONGO_INITDB_ROOT_PASSWORD=dhs
    ports:
      - "27017:27017"
#    volumes:
#      - ./src/main/resources/docker/create-gridfs-db.js:/docker-entrypoint-initdb.d/create-gridfs-db.js:ro
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 30s
      timeout: 10s
      retries: 3
