server:
  port: 8080
  servlet:
    context-path: /dhs

spring:
  application:
    name: document-handler-service
  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 200MB
  data:
    mongodb:
      authentication-database: admin
      host: localhost
      port: 27017
      database: documents
      username: dhs
      password: dhs
      options:
        maxConnectionIdleTime: 60000 # set the maxConnectionIdleTime to 60 seconds
        connectTimeout: 8000 # Set the connection timeout to 8 seconds
        socketTimeout: 30000 # Set the socket timeout to 30 seconds

logging:
  level:
    org.apache.tomcat: OFF
    org.apache.catalina: OFF
    org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: ERROR
    root: INFO
    ru.rudikov: DEBUG