server:
  port: 8080
  servlet:
    context-path: /dhs

spring:
  application:
    name: document-handler-service
  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 200MB
  data:
    mongodb:
      authentication-database: admin
      authentication-mechanism: SCRAM-SHA-1
      host: localhost
      port: 27017
      database: documents
      username: dhs
      password: dhs

logging:
  level:
    org.apache.tomcat: OFF
    org.apache.catalina: OFF
    org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: ERROR
    root: INFO
    ru.rudikov: DEBUG