server:
  port: 8080
  servlet:
    context-path: /dhs

spring:
  application:
    name: document-handler-service
  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 200MB
  data:
    mongodb:
      port: 27017
      host: localhost
      database: documents

logging:
  level:
    org.apache.tomcat: OFF
    org.apache.catalina: OFF
    org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: ERROR
    root: INFO
    ru.rudikov: DEBUG

storage:
  location: documents